apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: customerrequestcount
  namespace: istio-system
spec:
  value: "1"
  dimensions:
    method: request.method | "unknown"
    path: request.path | "unknown"
    useragent: request.useragent | "unknown"
    destination: destination.service.name | "unknown"
    code: response.code | 200
  monitored_resource_type: '"UNSPECIFIED"'
---
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: prometheus
  namespace: istio-system
spec:
  compiledAdapter: prometheus
  params:
    metrics:
    - name: customer_request_count
      instance_name: customerrequestcount.metric.istio-system
      kind: COUNTER
      label_names:
      - method
      - path
      - useragent
      - destination
      - code
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: customerprom
  namespace: istio-system
spec:
  actions:
  - handler: prometheus
    instances:
    - customerrequestcount.metric