apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  match: match(request.headers["cookie"], "user=tester") == false
  actions:
  - handler: handler.memquota
    instances:
    - requestcount.quota