apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: frontend-viewer
  namespace: weather
spec:
  rules:
  - services: ["frontend.weather.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-frontend-viewer
  namespace: weather
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "frontend-viewer"