apiVersion: config.istio.io/v1alpha2
kind: listchecker
metadata:
  name: advertisementwhitelist
spec:
  overrides: ["frontend"] 
  blacklist: false
---
apiVersion: config.istio.io/v1alpha2
kind: listentry
metadata:
  name: advertisementsource
spec:
  value: source.labels["app"]
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: check
spec:
  match: destination.labels["app"] == "advertisement"
  actions:
  - handler: advertisementwhitelist.listchecker
    instances:
    - advertisementsource.listentry